### ISSUE TITLE
UI for feedback of website

### ISSUE THREAD

**Issue by salayha** [bilalshahzad139/EADProject#52]
I will be creating a page that will open once a user signs out of his/her account in order to collect feedback on our website.
Some basic questioning will include:
User's Experience on the website (Satisfactory/Unsatisfactory)
How he got to know about our website (Family/Friends/Ads)
What is the one thing that we can do better that would help us to better serve him? (Describe)
Is he willing to enthusiastically recommend us to a someone today? (Yes/No/Maybe)

**Comment by usama4414** [comment]
So you're only working on the UI?

**Comment by salayha** [comment]
Yes.

**Comment by muhammad-bilal-ali** [comment]
@salayha 
I am working on issue  #74 (dataBase of Feedback),
Let me know when UI completed.

**Comment by salayha** [comment]
@muhammadbilalali1799  Okay.

**Comment by usama4414** [comment]
@salayha  @muhammadbilalali1799  
i've now updated this feature, UI is fine, Client Side Validation is Enabled, and form is submitting data to the controller.... @muhammadbilalali1799  use that controller to save the data in the data base.... commit in the same existing branch so that feature can be reviewed by us, then we'll make a PR.

**Comment by usama4414** [comment]
@muhammadbilalali1799  our work is done...UI is designed.... client side validations are added...and form is submitting data to a controller in User controller....Use that controller in order to save data in database...push that whole code into your feature branch and make a PR.
